import Feature from '@/components/Feature/Feature';
import Footer from '@/components/Footer/Footer';
import Header from '@/components/Header/Header';
import Slider from '@/components/Slider/Slider';
import type { NextPage } from 'next';
import Head from 'next/head';

const Home: NextPage = () => {
	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main>
				<Header />
				<Slider />
				<Feature />
			</main>
				
			<Footer />
		</div>
	);
};

export default Home;
